import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Footer from "./components/Footer/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body
        className="{`${geistSans.variable} ${geistMono.variable} antialiased`} bg-white"
      >
        <div className="bg-base-200">
          <Navbar />
        </div>
        <div className="min-h-screen  py-20 px-6">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
